services:
  gateway:
    build: gateway
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=hp
      - SPRING_DATASOURCE_PASSWORD=password

  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=hp
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hp -d shareit"]
      interval: 5s
      timeout: 5s
      retries: 10